### ISSUE TITLE
Dynamically set path for checkXauth

### ISSUE THREAD

**Issue by mauvehed** [musicmancorley/BriarIDS#9] opened 2017-04-30 20:38 UTC
While doing this install I needed to SSH as root and as such the hardcoded path in checkXauth.sh failed
```
ls /home/pi/.Xauthority > /dev/null

if [ "$?" == "0" ]; then
sudo cp /home/pi/.Xauthority /root/
```

I'd suggest doing something like 
```
ls $HOME/.Xauthority > /dev/null

if [ "$?" == "0" ]; then
sudo cp $HOME/pi/.Xauthority /root/`
```
instead so as many users may not do this as the default "pi" account.

Additionally, as I did this as root the "cp" was redundant so you may want to add a check for whether the user is root and if so, skip the "cp".

**Comment by mauvehed** [comment] 2017-04-30 20:40
Actually, it would be even smarter to verify if $HOME/.Xauthority even exists and if not, throw an error.

**Comment by g3tsyst3m** [comment] 2017-05-04 15:00
changes have been made.  I appreciate it @mauvehed 
I noticed two things.  If a user simply ssh'ed into the box as root it appears nothing further is required concerning.Xauthority permissions
If a user ssh'ed into the box as pi, and tried sudo python BriarIDS.py they would experience .Xauthority permission issues due to trying to run an X session as root without the .Xauthority file created

try out the recent update and see how that cooperates for you

**Comment by mauvehed** [comment] 2017-05-05 02:21
@musicmancorley Will try and check it out this weekend, busy today/tomorrow. I see you commented a bunch out, but I'm not sure the really covers all use cases. I don't use "pi" as my non-root user. I created my own, which I was initially using until I encountered problems and then started SSHing as root. So if you simply check for xauthority in root and assume the current user is "pi" that seems like it might still fail.

Either the script and it's checks need to be more dynamic, or the documentation for install needs to be more specific. I will say, I felt like a lot of the documentation was lacking or not straight forward. But let me follow up with that after a fresh reinstall and test. I'm kind of a documentation fiend.

**Comment by g3tsyst3m** [comment] 2017-05-05 03:03
good deal.  It works for me SSH'ing as root, creates the .Xauthority file even though it may say one does not exist, and loads the GUI as expected.  I would ideally like to devote more time to documentation and I do appreciate your honest feedback.  I'll do what I can to make things easier and more understandable.  If you find specific areas of the installation that could be more clear in the documentation let me know and I'll see if I can address them.  The WIKI could definitely use a tune up as well as the installation page in general.

**Comment by g3tsyst3m** [comment] 2017-05-06 15:36
made some more updates to checkauth and also elaborated more on the functionality of the Briar menu :)
It is definitely not exhaustive but I'll be honest, I build documentation around user feedback.  The more I get the better the documentation will be.  Your input has been very helpful.  Thx again

**Comment by g3tsyst3m** [comment] 2017-05-16 19:24
closing this as the current solution will provide a GUI as intended, regardless of warnings or redundancy.  I will continue to explore additional options to differentiate between sudo and root user, but for the time being the code contained within this script should cooperate for everyone using sudo or root.  I encourage anyone who wishes to improve this code or other sections to fork the repo!  thx

**Closed as completed by g3tsyst3m** 2017-05-16 19:24 UTC
